server {
    listen          80;
    server_name     immy_cdn;

    location /files/ {
        alias /usr/share/nginx/html/files/;
    }

    location /public/ {
        alias /usr/share/nginx/html/public/;

        autoindex on;
        autoindex_format json;

        add_header Access-Control-Allow-Origin "http://localhost:5173" always;
    }
}
